set-option -sg escape-time 10
set-option -g default-terminal "screen-256color"
set-option -g focus-events on
set-option -a terminal-features xterm-256color:RGB
set -g status-interval 2
set -g status-right-length 41
set -g status-right '#(path="#{pane_current_path}"; len=${#path}; [ $len -gt 30 ] && echo "...${path: -30}" || echo "$path") | %H:%M'
set-option -g status-style fg=colour108
set-option -g window-status-separator ' '
set-option -g window-status-current-style fg=colour15,bg=colour22,bold
set -g mouse on
